name: 'merlinco_apothecaries'
version: '1.0.0'
config-version: 2

profile: 'sa_snowflake'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  merlinco_apothecaries:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +tags: ['core_lab']
      +materialized: table

seeds:
  merlinco_apothecaries:
    +enabled: false
    +database: raw
    +schema: merlinco_apothecaries
    grimoire_crm:
      +tags: ['crm']
    abra_pos:
      +tags: ['pos']
    alembic_ops:
      +tags: ['ops']
flags:
  require_generic_test_arguments_property: true